INSERT INTO authors (author_id, first_name, last_name) VALUES
                                                        (1, 'F. Scott', 'Fitzgerald'),
                                                        (2, 'Harper', 'Lee'),
                                                        (3, 'George', 'Orwell'),
                                                        (4, 'Jane', 'Austen'),
                                                        (5, 'Herman', 'Melville'),
                                                        (6, 'J.D.', 'Salinger'),
                                                        (8, 'Leo', 'Tolstoy'),
                                                        (9, 'Fyodor', 'Dostoevsky'),
                                                        (10, 'Homer', ''),
                                                        (11, 'Dante', 'Alighieri'),
                                                        (12, 'Aldous', 'Huxley'),
                                                        (15, 'Suzanne', 'Collins'),
                                                        (16, 'Stephen', 'King'),
                                                        (17, 'Stieg', 'Larsson'),
                                                        (19, 'Khaled', 'Hosseini'),
                                                        (20, 'Yann', 'Martel'),
                                                        (21, 'Markus', 'Zusak'),
                                                        (23, 'L.M.', 'Montgomery'),
                                                        (24, 'Antoine de', 'Saint-Exupéry'),
                                                        (25, 'Arthur', 'Conan Doyle'),
                                                        (26, 'Alexandre', 'Dumas'),
                                                        (27, 'Miguel de', 'Cervantes'),
                                                        (28, 'Emily', 'Brontë'),
                                                        (29, 'Emily', 'Henry');

INSERT INTO books (title, author_id, price, stock, category, published_date, publisher) VALUES
                                                                                           ('The Great Gatsby', 1, 43.99, 50, 'Fiction', '1925-04-10', 'Scribner'),
                                                                                           ('To Kill a Mockingbird', 2, 35.99, 30, 'Fiction', '1960-07-11', 'HarperCollins'),
                                                                                           ('Pride and Prejudice', 4, 39.99, 25, 'Romance', '1813-01-28', 'Penguin Books'),
                                                                                           ('Moby-Dick', 5, 59.99, 15, 'Adventure', '1851-10-18', 'Vintage'),
                                                                                           ('The Catcher in the Rye', 6, 47.99, 35, 'Fiction', '1951-07-16', 'Macmillan'),
                                                                                           ('War and Peace', 8, 79.99, 10, 'Historical Fiction', '1869-01-01', 'Random House'),
                                                                                           ('Crime and Punishment', 9, 75.99, 20, 'Crime', '1866-01-01', 'Simon & Schuster'),
                                                                                           ('The Odyssey', 10, 37.99, 40, 'Epic Poetry', '800-01-01', 'Hachette'),
                                                                                           ('The Divine Comedy', 11, 63.99, 12, 'Poetry', '1320-01-01', 'Bloomsbury'),
                                                                                           ('Brave New World', 12, 41.99, 50, 'Dystopian', '1932-01-01', 'Alfred A. Knopf'),
                                                                                           ('Go Set a Watchman', 2, 36.99, 35, 'Fiction', '2015-07-14', 'Penguin Books'),
                                                                                           ('Animal Farm', 3, 47.99, 45, 'Satire', '1945-08-17', 'Random House'),
                                                                                           ('Billy Budd', 5, 59.99, 20, 'Adventure', '1891-11-01', 'Macmillan'),
                                                                                           ('The Hunger Games', 15, 57.99, 50, 'Dystopian', '2008-09-14', 'Scribner'),
                                                                                           ('The Shining', 16, 51.99, 35, 'Horror', '1977-01-28', 'HarperCollins'),
                                                                                           ('The Girl with the Dragon Tattoo', 17, 55.99, 40, 'Mystery', '2005-01-01', 'Vintage'),
                                                                                           ('The Kite Runner', 19, 53.99, 30, 'Historical Fiction', '2003-05-29', 'Simon & Schuster'),
                                                                                           ('Life of Pi', 20, 45.99, 20, 'Adventure', '2001-09-11', 'Alfred A. Knopf'),
                                                                                           ('The Book Thief', 21, 51.99, 25, 'Historical Fiction', '2005-03-14', 'Bloomsbury'),
                                                                                           ('Anne of Green Gables', 23, 37.99, 50, 'Children’s Fiction', '1908-01-01', 'Hachette'),
                                                                                           ('The Little Prince', 24, 41.99, 35, 'Children’s Fiction', '1943-04-06', 'Penguin Books'),
                                                                                           ('The Adventures of Sherlock Holmes', 25, 51.99, 45, 'Mystery', '1892-10-14', 'Macmillan'),
                                                                                           ('The Three Musketeers', 26, 73.99, 15, 'Historical Fiction', '1844-01-01', 'Random House'),
                                                                                           ('Don Quixote', 27, 79.99, 10, 'Adventure', '1615-01-01', 'Vintage'),
                                                                                           ('Wuthering Heights', 28, 39.99, 25, 'Gothic Fiction', '1847-12-01', 'Alfred A. Knopf'),
                                                                                           ('Beach Read', 29, 49.99, 40, 'Romance', '2020-05-19', 'Hachette');
