INSERT INTO books (book_id, title, author, price, stock, category, published_date) VALUES
                                                                                       ('1', 'The Great Gatsby', 'F. Scott Fitzgerald', 43.99, 50, 'Classic Literature', '1925-04-10'),
                                                                                       ('2', 'To Kill a Mockingbird', 'Harper Lee', 35.99, 30, 'Classic Literature', '1960-07-11'),
                                                                                       ('3', '1984', 'George Orwell', 49.99, 40, 'Dystopian', '1949-06-08'),
                                                                                       ('4', 'Pride and Prejudice', 'Jane Austen', 39.99, 25, 'Romance', '1813-01-28'),
                                                                                       ('5', 'Moby-Dick', 'Herman Melville', 59.99, 15, 'Classic Literature', '1851-10-18'),
                                                                                       ('6', 'The Catcher in the Rye', 'J.D. Salinger', 47.99, 35, 'Classic Literature', '1951-07-16'),
                                                                                       ('7', 'The Hobbit', 'J.R.R. Tolkien', 55.99, 45, 'Fantasy', '1937-09-21'),
                                                                                       ('8', 'War and Peace', 'Leo Tolstoy', 79.99, 10, 'Historical Fiction', '1869-01-01'),
                                                                                       ('9', 'Crime and Punishment', 'Fyodor Dostoevsky', 75.99, 20, 'Psychological Fiction', '1866-01-01'),
                                                                                       ('10', 'The Odyssey', 'Homer', 37.99, 40, 'Epic Poetry', '800-01-01'),
                                                                                       ('11', 'The Divine Comedy', 'Dante Alighieri', 63.99, 12, 'Epic Poetry', '1320-01-01'),
                                                                                       ('12', 'Brave New World', 'Aldous Huxley', 41.99, 50, 'Dystopian', '1932-01-01'),
                                                                                       ('13', 'The Road', 'Cormac McCarthy', 33.99, 30, 'Dystopian', '2006-09-26'),
                                                                                       ('14', 'The Alchemist', 'Paulo Coelho', 47.99, 60, 'Philosophical Fiction', '1988-01-01'),
                                                                                       ('15', 'The Lord of the Rings', 'J.R.R. Tolkien', 91.99, 25, 'Fantasy', '1954-07-29'),
                                                                                       ('17', 'The Hunger Games', 'Suzanne Collins', 57.99, 50, 'Young Adult', '2008-09-14'),
                                                                                       ('18', 'The Shining', 'Stephen King', 51.99, 35, 'Horror', '1977-01-28'),
                                                                                       ('19', 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 55.99, 40, 'Mystery', '2005-01-01'),
                                                                                       ('20', 'The Fault in Our Stars', 'John Green', 39.99, 45, 'Young Adult', '2012-01-10'),
                                                                                       ('21', 'The Kite Runner', 'Khaled Hosseini', 53.99, 30, 'Drama', '2003-05-29'),
                                                                                       ('22', 'Life of Pi', 'Yann Martel', 45.99, 20, 'Adventure', '2001-09-11'),
                                                                                       ('23', 'The Book Thief', 'Markus Zusak', 51.99, 25, 'Historical Fiction', '2005-03-14'),
                                                                                       ('24', 'The Secret Garden', 'Frances Hodgson Burnett', 33.99, 40, 'Children Literature', '1911-01-01'),
                                                                                       ('25', 'Anne of Green Gables', 'Lucy Maud Montgomery', 37.99, 50, 'Children Literature', '1908-01-01'),
                                                                                       ('26', 'The Little Prince', 'Antoine de Saint-Exupéry', 41.99, 35, 'Children Literature', '1943-04-06'),
                                                                                       ('27', 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 51.99, 45, 'Mystery', '1892-10-14'),
                                                                                       ('28', 'The Count of Monte Cristo', 'Alexandre Dumas', 73.99, 15, 'Adventure', '1844-01-01'),
                                                                                       ('29', 'Don Quixote', 'Miguel de Cervantes', 79.99, 10, 'Classic Literature', '1615-01-01'),
                                                                                       ('30', 'Wuthering Heights', 'Emily Brontë', 39.99, 25, 'Romance', '1847-12-01');
